# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_surfdata": "00_load_videos.ipynb",
         "SURF_SPOTS": "00_load_videos.ipynb",
         "save_forecast_and_stream": "00_load_videos.ipynb",
         "video_length_s": "00_load_videos.ipynb",
         "decode_frame_sequence": "00_load_videos.ipynb",
         "dense_optical_flow": "02_wave_detection.ipynb",
         "heatmap_fit": "02_wave_detection.ipynb",
         "trim_image": "03_perspective_transform.ipynb",
         "avg_wave_flows": "02_wave_detection.ipynb",
         "accumulate_flows": "02_wave_detection.ipynb",
         "fit_mean_flows": "02_wave_detection.ipynb",
         "get_sample_start_times": "02_wave_detection.ipynb",
         "detect_surfzone": "02_wave_detection.ipynb",
         "normalized": "03_perspective_transform.ipynb",
         "shift_img": "03_perspective_transform.ipynb",
         "fit_line": "03_perspective_transform.ipynb",
         "rotate_bound": "03_perspective_transform.ipynb",
         "flow_mag_at_point": "03_perspective_transform.ipynb",
         "fit_surfzone_homography_points": "03_perspective_transform.ipynb",
         "pix_to_crop_from_dir": "03_perspective_transform.ipynb",
         "find_crop_range": "03_perspective_transform.ipynb",
         "image_flow_magnitude": "03_perspective_transform.ipynb",
         "fit_homography_to_mean_flow": "03_perspective_transform.ipynb",
         "warp_trimmed_image": "03_perspective_transform.ipynb",
         "find_surfspot_calibration_params": "03_perspective_transform.ipynb",
         "normalize_image": "03_perspective_transform.ipynb",
         "plot_mean_flow_mag": "03_perspective_transform.ipynb",
         "run_surfcam_calibration": "03_perspective_transform.ipynb",
         "video_file_to_calibrated_image_tensors": "03_perspective_transform.ipynb",
         "graph_entry_to_string": "04_graph_utilities.ipynb",
         "describe_graph": "04_graph_utilities.ipynb",
         "short_func_label": "04_graph_utilities.ipynb",
         "full_func_label": "04_graph_utilities.ipynb",
         "func_node_name": "04_graph_utilities.ipynb",
         "to_digraph": "04_graph_utilities.ipynb",
         "digraph_to_png": "04_graph_utilities.ipynb",
         "visualize": "04_graph_utilities.ipynb"}

modules = ["load_videos.py",
           "detection.py",
           "transform.py",
           "graphutils.py"]

doc_url = "https://sjobeek.github.io/surfbreak/"

git_url = "https://github.com/sjobeek/surfbreak/tree/master/"

def custom_doc_links(name): return None
