# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_surfdata": "00_load_videos.ipynb",
         "SURF_SPOTS": "00_load_videos.ipynb",
         "save_forecast_and_stream": "00_load_videos.ipynb",
         "video_length_s": "00_load_videos.ipynb",
         "decode_frame_sequence": "00_load_videos.ipynb",
         "dense_optical_flow": "02_wave_detection.ipynb",
         "heatmap_fit": "02_wave_detection.ipynb",
         "trim_image": "03_perspective_transform.ipynb",
         "avg_wave_flows": "02_wave_detection.ipynb",
         "detect_surfzone": "02_wave_detection.ipynb",
         "normalized": "03_perspective_transform.ipynb",
         "vector_tile": "03_perspective_transform.ipynb"}

modules = ["load_videos.py",
           "detection.py",
           "transform.py"]

doc_url = "https://sjobeek.github.io/surfbreak/"

git_url = "https://github.com/sjobeek/surfbreak/tree/master/"

def custom_doc_links(name): return None
