# AUTOGENERATED! DO NOT EDIT! File to edit: 00_load_videos.ipynb (unless otherwise specified).

__all__ = ['get_surfdata', 'surf_spots']

# Cell
import requests
def get_surfdata(spotid, forecast=True):
    """Retrieves current and forecast surf conditions for the next 24 hours from Surfline.
       Setting forecast=False will keep only the current conditions"""
    payload = {"spotId":spotid, "days":"1", "intervalHours":"6"}
    wave_data = requests.get("https://services.surfline.com/kbyg/spots/forecasts/wave", params=payload).json()
    payload["intervalHours"] = "2"
    wind_data = requests.get("https://services.surfline.com/kbyg/spots/forecasts/wind", params=payload).json()
    tides_data = requests.get("https://services.surfline.com/kbyg/spots/forecasts/tides", params=payload).json()
    weather_data = requests.get("https://services.surfline.com/kbyg/spots/forecasts/weather", params=payload).json()

    surf_data = wave_data
    surf_data['associated']['spotId'] = spotid
    surf_data['data']['wind'] = wind_data['data']['wind']
    surf_data['associated']['tideLocation'] = tides_data['associated']['tideLocation']
    surf_data['data']['tides'] = tides_data['data']['tides']
    surf_data['data']['weather'] = weather_data['data']['weather']

    if not forecast:
        for data_type in surf_data['data'].keys():
            surf_data['data'][data_type] = [surf_data['data'][data_type][0]]
    return surf_data

# Cell
surf_spots = {"shirahama": {"cam_url": "https://www.youtube.com/watch?v=WbRbWJZ7ZH0",
                            "spotid": "584204204e65fad6a77098c4"}
             }